config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  devise_for :authors

  resources :authors do
    resources :articles
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author
  has_many :votes
  has_many :article_categories
  has_many :categories, through: :article_categories

  def article_categories
    categories.collect(&:name).join(', ')
  end

  def article_categories=(string)
    categories_names = string.split(',').collect { |s| s.strip.downcase }.uniq
    new_or_found_categories = categories_names.collect { |name| Category.find_or_create_by(name: name) }
    self.categories = new_or_found_categories
  end
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :votes
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :author
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @author = Author.find(current_author.id)
    @category = Category.new
    @article = Article.new
  end

  def create
    @author = Author.find(params[:author_id])
    @article = @author.articles.build(article_params)
    # categories = params[:category].split(',');
    # categories.each do |cat|
      # @category = Category.new(name: 'cat');
      # if @category.save
        # @article.categories << @category
        # @category.articles << @article
      # end
    # end

    if @article.save
      redirect_to root_path
    end
  end

  def article_categories
    categories.join(', ')
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :article_categories)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/articles/index.html.erb
<h1>Hello, World!</h1>

<ul>
  <% if @articles.any? %>
    <% @articles.each do |article| %>
      <li>Article title: <%= article.title %>, Author: <%= article.author.email %>, Content: <%= article.body %>,
                  Categories: <% article.categories.each do |cat| %>
                                <%= cat.name %>
                              <% end %></li>
    <% end %>
  <% end %>
</ul>

app/views/articles/new.html.erb
<div class="container d-flex align-items-center flex-column">
  <h2 class="mb-3">Create a new article</h2>

    <%= form_with(model: [@author, @article], class:'w-75') do |f| %>
      <div class="mb-3 w-100">
        <%= f.label :title, class: 'form-label' %><br />
        <%= f.text_field :title, autofocus: true, autocomplete: "title", class: 'form-control' %>
      </div>

      <div class="mb-3 w-100">
        <%= f.label 'Content', class: 'form-label' %><br />
        <%= f.text_area(:body, rows: 8, class:'form-control') %>
      </div>

      <div class="mb-3 w-100">
        <%= f.label 'Categories', class: 'form-label' %><br />
        <%= f.text_field :article_categories, autocomplete: 'category', class: 'form-control' %>
      </div>

      <div class="actions w-100 text-center">
        <%= f.submit "CREATE ARTICLE", class: 'btn btn-primary' %>
      </div>
    <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "CodingStyle", root_path, class: 'navbar-brand' %>
    <button
      class="navbar-toggler" 
      type="button" 
      data-bs-toggle="collapse" 
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
      </ul>
        <% if author_signed_in? %>
          <%= link_to 'CREATE ARTICLE', new_author_article_path(current_author.id), class: 'btn btn-outline-primary me-2' %>
          <%= link_to 'SIGN OUT', destroy_author_session_path, method: :delete, class: 'btn btn-outline-success' %>
        <% else %>
          <%= link_to 'SIGN IN', new_author_session_path, class: 'btn btn-outline-success' %>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeStyle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" 
      crossorigin="anonymous"
    >
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= render './layouts/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <script 
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" 
      crossorigin="anonymous">
    </script>
  </body>
</html>